# Generated by Django 3.1.7 on 2021-02-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('sort_title', models.CharField(max_length=128, unique=True)),
                ('controller_support', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Date Modified')),
                ('description', models.TextField(blank=True, max_length=512)),
                ('developer', models.CharField(blank=True, max_length=128)),
                ('esrb', models.CharField(blank=True, choices=[('EC', 'Early Childhood'), ('E', 'Everyone'), ('E10+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature')], max_length=4, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=128, null=True)),
                ('player', models.CharField(blank=True, choices=[('1', '1 Player'), ('2', '2 Players'), ('2-4', '2-4 Players'), ('4+', '4+ Players')], max_length=10, null=True)),
                ('online_multiplayer', models.BooleanField(default=False)),
                ('publisher', models.CharField(blank=True, max_length=128)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('region', models.CharField(choices=[('EU', 'Europe'), ('NA', 'North America'), ('JP', 'Japan')], default='NA', max_length=2, null=True)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('store', models.CharField(blank=True, choices=[('BLIZZARD', 'Blizzard'), ('EPIC', 'Epic Games'), ('GOG', 'GOG.com'), ('HUMBLE', 'Humble Bundle'), ('ITCH', 'itch.io'), ('MICROSOFT', 'Microsoft'), ('NINTENDO', 'Nintendo'), ('PSN', 'PlayStation Network')], max_length=10, null=True)),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platform')),
            ],
        ),
    ]
