# Generated by Django 3.1.7 on 2021-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210228_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='launcher',
            field=models.CharField(max_length=192, null=True),
        ),
    ]
