# Generated by Django 3.1.7 on 2021-02-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210228_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='title',
        ),
    ]
