# Generated by Django 3.1.14 on 2022-10-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20220814_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='alt_title',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
