# Generated by Django 3.1.7 on 2021-02-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_platform_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='launcher',
            field=models.CharField(blank=True, max_length=192, null=True),
        ),
    ]
