# Generated by Django 3.1.7 on 2021-02-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20210228_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='region',
            field=models.CharField(blank=True, choices=[('EU', 'Europe'), ('NA', 'North America'), ('JP', 'Japan')], default='NA', max_length=2, null=True),
        ),
    ]
