# Generated by Django 4.1.5 on 2023-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_auto_20221023_0026"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="save_path",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
