# Generated by Django 3.1.7 on 2021-02-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20210228_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='icons',
            new_name='icon',
        ),
    ]
