# Generated by Django 4.1.5 on 2023-05-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_game_save_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="save_path",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
