# Generated by Django 4.1.5 on 2023-05-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_game_save_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="engine",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Engine"
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="esrb",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "Everyone"),
                    ("E10", "Everyone 10+"),
                    ("T", "Teen"),
                    ("M", "Mature"),
                    ("AO", "Adults Only"),
                ],
                max_length=4,
                null=True,
                verbose_name="ESRB",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="store",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BLIZZARD", "Blizzard"),
                    ("GOG", "GOG.com"),
                    ("HUMBLE", "Humble Bundle"),
                    ("ITCH", "itch.io"),
                    ("PSN", "PlayStation Network"),
                    ("STEAM", "Steam"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
