# Generated by Django 3.1.7 on 2021-03-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20210318_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='games.Tag'),
        ),
    ]
