# Generated by Django 3.1.8 on 2021-04-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20210318_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='kid_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(blank=True, to='games.Tag'),
        ),
    ]
