# Generated by Django 3.1.8 on 2021-04-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210420_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='icon',
        ),
        migrations.AddField(
            model_name='game',
            name='co_op',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='esrb',
            field=models.CharField(blank=True, choices=[('EC', 'Early Childhood'), ('E', 'Everyone'), ('E10+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature'), ('AO', 'Adults Only')], max_length=4, null=True, verbose_name='ESRB'),
        ),
    ]
