# Generated by Django 3.1.8 on 2021-04-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20210420_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='path',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='esrb',
            field=models.CharField(blank=True, choices=[('E', 'Everyone'), ('E10+', 'Everyone 10+'), ('T', 'Teen'), ('M', 'Mature'), ('AO', 'Adults Only')], max_length=4, null=True, verbose_name='ESRB'),
        ),
        migrations.AlterField(
            model_name='game',
            name='store',
            field=models.CharField(blank=True, choices=[('BLIZZARD', 'Blizzard'), ('EPIC', 'Epic Games'), ('GOG', 'GOG.com'), ('HUMBLE', 'Humble Bundle'), ('ITCH', 'itch.io'), ('MICROSOFT', 'Microsoft'), ('NINTENDO', 'Nintendo'), ('PSN', 'PlayStation Network'), ('STEAM', 'Steam')], max_length=10, null=True),
        ),
    ]
