# Generated by Django 3.1.8 on 2021-04-22 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20210421_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='installed',
            field=models.BooleanField(default=False),
        ),
    ]
