# Generated by Django 3.1.8 on 2021-04-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='installed_remote',
            field=models.BooleanField(default=False),
        ),
    ]
