# Generated by Django 3.1.8 on 2021-04-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_game_installed_remote'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steamid',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
