# Generated by Django 3.1.8 on 2021-04-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_game_steamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='steamid',
        ),
    ]
