# Generated by Django 3.1.8 on 2021-05-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_remove_game_steamid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='installed_remote',
        ),
        migrations.RemoveField(
            model_name='game',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='launcher',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='year',
        ),
        migrations.AddField(
            model_name='game',
            name='steam_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
