# Generated by Django 3.1.8 on 2021-05-02 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20210502_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='image',
        ),
    ]
