# Generated by Django 3.1.8 on 2021-05-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_remove_platform_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='required_files',
            field=models.TextField(blank=True, null=True),
        ),
    ]
