# Generated by Django 3.1.12 on 2021-07-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_auto_20210712_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ram',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='RAM'),
        ),
    ]
