# Generated by Django 3.1.12 on 2021-07-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_auto_20210712_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='path',
        ),
        migrations.AddField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('App', 'Application'), ('EMU', 'Emulator')], max_length=10, null=True),
        ),
    ]
