# Generated by Django 3.1.12 on 2021-07-17 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_auto_20210716_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('APP', 'Application'), ('EMU', 'Emulator')], max_length=10, null=True),
        ),
    ]
