# Generated by Django 3.1.12 on 2021-08-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_auto_20210725_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=1024)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='kid_friendly',
        ),
        migrations.AddField(
            model_name='game',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.collection'),
        ),
    ]
