# Generated by Django 3.1.12 on 2021-08-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_auto_20210806_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='games/icons/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(blank=True, choices=[('1', '1 Player'), ('2', '2 Players'), ('2-3', '2-3 Players'), ('2-4', '2-4 Players'), ('4+', '4+ Players')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.ImageField(blank=True, null=True, upload_to='games/title/'),
        ),
    ]
