# Generated by Django 3.1.12 on 2021-08-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0028_auto_20210817_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='games/title/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='NULL', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
