# Generated by Django 3.1.12 on 2021-09-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_auto_20210817_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='manual',
            field=models.FileField(blank=True, null=True, upload_to='games/manual/'),
        ),
    ]
