# Generated by Django 3.1.12 on 2021-10-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_game_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='perspective',
            field=models.CharField(blank=True, choices=[('FPP', '1st-person'), ('TPP', '3rd-person'), ('BEHIND', 'Behind View'), ('BIRDSEYE', "Bird's Eye View"), ('SIDEVIEW', 'Side View'), ('TEXT', 'Text-Based'), ('TOPDOWN', 'Top Down')], max_length=8, null=True),
        ),
    ]
