# Generated by Django 3.1.12 on 2021-10-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_game_perspective'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='kid_game',
            field=models.BooleanField(default=False),
        ),
    ]
