# Generated by Django 3.1.12 on 2021-11-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0032_game_kid_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='games/screenshot/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.CharField(blank=True, choices=[('1', '1 Player'), ('2', '2 Players'), ('3', '3 Players'), ('4', '4 Players'), ('8', '8 Players')], max_length=10, null=True),
        ),
    ]
