# Generated by Django 3.1.12 on 2021-11-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0033_auto_20211101_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to='games/display/'),
        ),
    ]
