# Generated by Django 3.1.12 on 2021-11-06 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_game_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='installed',
        ),
        migrations.AlterField(
            model_name='game',
            name='path',
            field=models.CharField(default='game.path', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
