# Generated by Django 3.1.12 on 2021-11-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_auto_20211105_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='perspective',
        ),
        migrations.RemoveField(
            model_name='game',
            name='required_files',
        ),
        migrations.AddField(
            model_name='game',
            name='translation',
            field=models.BooleanField(default=False),
        ),
    ]
