# Generated by Django 3.1.14 on 2022-01-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0036_auto_20211106_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='grid',
            field=models.ImageField(blank=True, null=True, upload_to='games/grid/'),
        ),
        migrations.AddField(
            model_name='game',
            name='grid_sm',
            field=models.ImageField(blank=True, null=True, upload_to='games/grid_sm/'),
        ),
    ]
