# Generated by Django 3.1.14 on 2022-01-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_auto_20220107_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='grid_sm',
            field=models.ImageField(blank=True, null=True, upload_to='games/grid_sm/', verbose_name='Banner'),
        ),
    ]
