# Generated by Django 3.1.14 on 2022-01-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0038_auto_20220107_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='grid_sm',
            new_name='banner',
        ),
    ]
