# Generated by Django 3.1.14 on 2022-01-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_auto_20220107_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='grid',
            new_name='header',
        ),
    ]
