# Generated by Django 3.1.14 on 2022-01-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_auto_20220107_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='games/header/'),
        ),
    ]
