# Generated by Django 3.1.14 on 2022-03-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0044_auto_20220107_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
