# Generated by Django 3.1.14 on 2022-08-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_remove_game_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='game',
            name='kid_game',
        ),
    ]
