#! /bin/bash

APP_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
APP_FILES="$HOME/.empr"
BROWSER="$APP_DIR/browser"
SERVER_URL="127.0.0.1:8088"

LOAD="--app=file://$APP_DIR/games/templates/gui/loading.html --user-data-dir=$APP_FILES/browser"

## Init
init(){
  $APP_DIR/empr init
  $APP_DIR/empr makemigrations
  $APP_DIR/empr migrate
  $APP_DIR/empr collectstatic -c --noinput
}

## Run server
run(){
  ## Start Django server
  $APP_DIR/empr runserver $SERVER_URL --noreload &

  ## Launch browser
  sleep 1
  $BROWSER/linux-x64/browser $LOAD

  ## Stop server
  pkill -f runserver
}

if [[ ! -d $APP_FILES ]]; then
  echo "No database found. Initiating..."
  init
  echo "Databse created. Staring app..."
  run
else
  run
fi
