#! /bin/bash

## Get config
APPDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
APPFILES="$HOME/.empr"
BROWSER="$APPDIR/browser"

URL="--app=file://$APPDIR/games/templates/gui/loading.html"

## Run server
$APPDIR/empr runserver 127.0.0.1:8088 --noreload &

## Launch browser
$BROWSER/linux-x64/browser $URL

## Stop server
pkill -f runserver
