#!/bin/bash

source $HOME/Applications/Empr/config/empr/settings.sh
FILE="$1"
BASENAME="$(basename $FILE)"
DIRNAME="$(dirname $FILE)"
PKGDIR="$CACHEDIR/pkg"
PLATFORM="$(basename $DIRNAME)"
GAME="${BASENAME%.*}"
GAMESDIR="$HOME/Games"
GAMEREPO="/mnt/games"

echo -e "
## DEBUGGING
------------
APPDB: $APPDB
APPDIR: $APPDIR
BASENAME: $BASENAME
CACHEDIR: $CACHEDIR
DIRNAME: $DIRNAME
FILE: $FILE
GAME: $GAME
GAMEREPO: $GAMEREPO
PKGDIR: $PKGDIR
PLATFORM: $PLATFORM
SQLITE: $SQLITE
UTILSDIR: $UTILSDIR
"

mkdir -p $PKGDIR/$GAME $GAMESDIR/$PLATFORM
cd $PKGDIR
cp -rv $FILE ./
#tar xvf $BASENAME -C $PKGDIR/$GAME
cp -v $PKGDIR/$GAME/* $GAMESDIR/$PLATFORM/
rm -rf $PKGDIR/*
